# Site
name: Distributor Resmi PT. Natural Nusantara Indonesia
description: PT. Natural Nusantara adalah perusahaan multinasional yang bergerak di bidang perdagangan produk agro kompleks, kesehatan, kecantikan dan kebutuhan rumah tangga berbasis organik.
meta_description: "PT. Natural Nusantara adalah perusahaan multinasional yang bergerak di bidang perdagangan produk agro kompleks, kesehatan, kecantikan dan kebutuhan rumah tangga berbasis organik.."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: 
email: 'rianifebryanti9@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'rianifebryanti'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  sal:
    name: Farhamdani
    display_name: Farhamdani
    gravatar: 7721a72ad4d230b361133727b1916b85
    email: farhamdani9@gmail.com
    web: https://www.brodanie.com/
    twitter: https://twitter.com/brodanieblog
    description: "Hanya seorang pria yang hobi merangkai kata-kata menjadi sebuah kalimat."
  john:
    name: Riani Febryanti
    display_name: Riani
    gravatar: 70ed949ecf971695bb35ca298efd4bbb
    email: rianifebryanti9@gmail.com
    web: https://naturalnusantara.me
    twitter: https://twitter.com/@
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
